apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: speedtest-scheduler
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: speedtest-scheduler
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - name: speedtest-scheduler
              image: k8s101registry.azurecr.io/speed-test-scheduler:0.0.1
              env:
                - name: KubeMQ_Channel
                  value: speedtest
                - name: KubeMQ_ClientID
                  value: speedtest-scheduler
                - name: KubeMQ_ServerAddress
                  value: kubemq-cluster-node:50000
                - name: Logging__LogLevel__Default
                  value: Debug
          restartPolicy: Never
