apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: speedtest-scheduler-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: speedtest-scheduler
        spec:
          imagePullSecrets:
            - name: regcred 
          containers:
          - name: speedtest-scheduler-cronjob
            image: k8s101registry.azurecr.io/speedtest-scheduler:latest
            env:
              - name: KubeMQ_Channel
                value: speedtest
              - name: KubeMQ_ClientID
                value: speedtest-scheduler
              - name: KubeMQ_ServerAddress
                value: kubemq-cluster:50000
              - name: Logging__LogLevel__Default
                value: Debug
          restartPolicy: Never