apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: speedtest-scheduler-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: silver-spade-key
          containers:
          - name: speedtest-scheduler-cronjob
            image: das-regestry:latest
            env:
              - name: channel
                value: speedtest
              - name: clinetID
                value: speedtest-scheduler
              - name: kubeMQAddress
                value: "kubemq-cluster:50000"
          restartPolicy: OnFailure
